//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerry.K3.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTION_JOB
    {
        public decimal UNID { get; set; }
        public long JOB_UNID { get; set; }
        public string SHPNO { get; set; }
        public string CONSOLNO { get; set; }
        public Nullable<long> CONSOLLOT_UNID { get; set; }
        public string BIZTYPE { get; set; }
        public string SHPTYPE { get; set; }
        public string OWNERID { get; set; }
        public string ACTION { get; set; }
        public string STATUS { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    }
}
