//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerry.K3.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOBLINK
    {
        public long SOURCE_UNID { get; set; }
        public string TYPE { get; set; }
        public long JOB_UNID { get; set; }
    }
}
